/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

tasks.jar {
    manifest {
        attributes("Main-Class" to "com.gabizou.Main")
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.gabizou.Main")
}
